
import { Language } from './types';

export const translations: Record<Language, any> = {
  en: {
    nav: { home: 'Home', materials: 'Materials', estimator: 'Estimator', locations: 'Locations', partner: 'Partner Login' },
    hero: {
      tagline: 'Leading Flooring Supplier in Kyrgyzstan',
      title_part1: 'Build Your',
      title_accent: 'Dream Home',
      title_part2: 'with TamSal',
      desc: 'Specializing in high-quality PVC panels, laminate, linoleum, and professional installation materials for Bishkek residents.',
      cta_browse: 'Browse Catalog',
      cta_ai: 'AI Estimator'
    },
    home: {
      core_inv: 'Our Specialized Range',
      core_desc: 'Premium selection of wall panels and flooring solutions.',
      view_all: 'View Full Inventory',
      trust_logs: 'Swift Logistics',
      trust_logs_desc: 'Dedicated fleet for same-day delivery across Bishkek city and suburbs.',
      trust_cert: 'Certified Quality',
      trust_cert_desc: 'Durable materials tested for the Kyrgyz climate and long-term use.',
      trust_ai: 'AI Assistance',
      trust_ai_desc: 'Next-gen calculation for flooring and paneling projects available 24/7.'
    },
    catalog: {
      categories: 'Categories',
      search: 'Search Products',
      results_for: 'Results for',
      found: 'items found',
      add: 'Add',
      no_found: 'No products found',
      no_found_desc: 'Try adjusting your filters or search query.'
    },
    calculator: {
      tag: 'Smart Tools',
      title: 'Project Estimator',
      desc: 'Estimate the amount of laminate, linoleum, or PVC panels you need for your space.',
      proj_type: 'Project Type',
      proj_type_ph: 'e.g. Laminate flooring, Bathroom paneling',
      dims: 'Dimensions',
      dims_ph: 'e.g. 20 sq.m or 3m x 4m',
      btn: 'Generate Estimation',
      btn_loading: 'Calculating...',
      results: 'Results',
      disclaimer: '* Disclaimer: These are estimates generated by AI based on standard layouts. Always allow for 5-10% wastage.'
    },
    contact: {
      title: 'Visit Our Locations',
      open_2gis: '2GIS',
      open_gmaps: 'Google Maps',
      call: 'Call Branch',
      delivery_title: 'Delivery Across Bishkek',
      delivery_desc: 'We deliver to all districts: Leninskiy, Oktyabrskiy, Pervomayskiy, Sverdlovskiy, and Chuy region suburbs.',
      next_day_title: 'Next-day Delivery',
      next_day_desc: 'Order before 4:00 PM to receive your materials the very next day. Our dedicated fleet ensures timely arrival at your construction site.',
      bulk_title: 'Bulk Order Discounts',
      bulk_desc: 'Planning a large project? We offer special pricing for orders over 100 sq.m. Contact our sales team for a personalized quote.',
      quick_tip: 'Interactive Map',
      tip_desc: 'Select a location on the left to see it on the map. You can use 2GIS or Google Maps for navigation.'
    },
    cart: {
      title: 'Your Cart',
      empty: 'Cart is empty',
      empty_desc: 'Add some materials to get started.',
      remove: 'Remove',
      subtotal: 'Subtotal',
      checkout: 'Checkout Now',
      secure: 'Secure checkout powered by Kyrgyz Pay'
    },
    footer: {
      desc: 'TamSal: Specialists in modern flooring and wall finishing solutions. Serving Kyrgyzstan since 2010.',
      nav: 'Navigation',
      contact: 'Contact',
      rights: '© 2024 TamSal. All rights reserved.',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      seismic: 'Quality Standards'
    },
    partner: {
      title: 'Partner with TamSal',
      subtitle: 'Join our network of professional installers and contractors in Bishkek.',
      company: 'Company Name',
      contact: 'Contact Person',
      phone: 'Phone Number',
      email: 'Email Address',
      type: 'Business Type',
      type_installer: 'Professional Installer',
      type_contractor: 'General Contractor',
      type_retailer: 'Retailer',
      type_designer: 'Interior Designer',
      message: 'Briefly describe your business',
      submit: 'Apply for Partnership',
      success_title: 'Application Received!',
      success_desc: 'Thank you for your interest. Our partnership manager will contact you within 24 hours to discuss terms and wholesale pricing.',
      back: 'Back to Home'
    },
    ai: {
      welcome: "Hello! I'm TamSal's AI expert. How can I help you with your flooring or paneling project today?",
      header: "TamSal Assistant",
      status: "Online | AI Consultant",
      input_ph: "Ask about laminate, PVC panels, or installation...",
      fact_check: "Fact-checked with Google"
    }
  },
  kg: {
    nav: { home: 'Башкы бет', materials: 'Материалдар', estimator: 'Эсептегич', locations: 'Даректер', partner: 'Өнөктөш кирүү' },
    hero: {
      tagline: 'Кыргызстандагы алдыңкы жеткирүүчү',
      title_part1: 'TamSal менен',
      title_accent: 'Кыялыңызды',
      title_part2: 'куруңуз',
      desc: 'Жогорку сапаттагы ПВХ панелдери, ламинат, линолеум жана кесипкөй орнотуу материалдары боюнча адистешкен.',
      cta_browse: 'Каталогду көрүү',
      cta_ai: 'AI Эсептегич'
    },
    home: {
      core_inv: 'Адистештирилген инвентарь',
      core_desc: 'Дубал панелдерин жана пол төшөлмөлөрүнүн премиум тандоосу.',
      view_all: 'Толук каталогду көрүү',
      trust_logs: 'Тез логистика',
      trust_logs_desc: 'Бишкек шаары жана четиндеги аймактарга ошол эле күнү жеткирүү.',
      trust_cert: 'Сертификатталган сапат',
      trust_cert_desc: 'Кыргызстандын климатына жана узак мөөнөттүү колдонууга текшерилген бышык материалдар.',
      trust_ai: 'AI Жардамы',
      trust_ai_desc: 'Пол жана дубал долбоорлорун эсептөө 24/7 жеткиликтүү.'
    },
    catalog: {
      categories: 'Категориялар',
      search: 'Материалдарды издөө',
      results_for: 'Издөө жыйынтыгы:',
      found: 'даана табылды',
      add: 'Кошуу',
      no_found: 'Продукт табылган жок',
      no_found_desc: 'Чыпкаларды же издөө сурооңузду өзгөртүп көрүңүз.'
    },
    calculator: {
      tag: 'Акылдуу куралдар',
      title: 'Долбоор эсептегичи',
      desc: 'Ламинат, линолеум же ПВХ панелдеринин керектүү көлөмүн эсептеңиз.',
      proj_type: 'Долбоордун түрү',
      proj_type_ph: 'Мисалы: ламинат төшөө, жуунуучу бөлмөнү ПВХ менен кооздоо',
      dims: 'Өлчөмдөрү',
      dims_ph: 'Мисалы: 20 кв.м же 3м x 4м',
      btn: 'Эсептөөнү баштоо',
      btn_loading: 'Эсептелүүдө...',
      results: 'Жыйынтыктар',
      disclaimer: '* Эскертүү: Бул стандарттык нормаларга негизделген AI эсептөөлөрү. Ар дайым 5-10% ашыкча материал алууну сунуштайбыз.'
    },
    contact: {
      title: 'Биздин даректер',
      open_2gis: '2GIS',
      open_gmaps: 'Google Карта',
      call: 'Чалуу',
      delivery_title: 'Бишкек боюнча жеткирүү',
      delivery_desc: 'Биз бардык райондорго: Ленин, Октябрь, Биринчи Май, Свердлов жана Чүй облусунун четки аймактарына жеткиребиз.',
      next_day_title: 'Эртеси күнү жеткирүү',
      next_day_desc: 'Материалдарды кийинки күнү алуу үчүн саат 16:00гө чейин заказ бериңиз. Биздин автопарк курулуш аянтыңызга өз убагында жеткирүүнү камсыздайт.',
      bulk_title: 'Дүң арзандатуулар',
      bulk_desc: 'Чоң долбоорду пландап жатасызбы? 100 кв.м ашкан заказдар үчүн атайын бааларды сунуштайбыз. Жеке сунуш алуу үчүн биздин сатуу бөлүмүнө кайрылыңыз.',
      quick_tip: 'Интерактивдүү карта',
      tip_desc: 'Картадан көрүү үчүн сол тараптагы даректи тандаңыз. 2GIS же Google Maps аркылуу жол алсаңыз болот.'
    },
    cart: {
      title: 'Сиздин корзинаңыз',
      empty: 'Корзина бош',
      empty_desc: 'Баштоо үчүн материалдарды кошуңуз.',
      remove: 'Өчүрүү',
      subtotal: 'Жалпы сумма',
      checkout: 'Сатып алуу',
      secure: 'Коопсуз төлөм Kyrgyz Pay аркылуу'
    },
    footer: {
      desc: 'TamSal: Заманбап пол жана дубал жасалгалоо чечимдери боюнча адистер. 2010-жылдан бери кызмат көрсөтөбүз.',
      nav: 'Навигация',
      contact: 'Байланыш',
      rights: '© 2024 TamSal. Бардык укуктар корголгон.',
      privacy: 'Купуялык саясаты',
      terms: 'Колдонуу шарттары',
      seismic: 'Сапат стандарттары'
    },
    partner: {
      title: 'TamSal менен өнөктөш болуңуз',
      subtitle: 'Бишкектеги кесипкөй орнотуучулар жана подрядчылар тармагына кошулуңуз.',
      company: 'Компаниянын аталышы',
      contact: 'Байланышуучу адам',
      phone: 'Телефон номери',
      email: 'Электрондук почта',
      type: 'Бизнес түрү',
      type_installer: 'Кесипкөй орнотуучу',
      type_contractor: 'Жалпы подрядчы',
      type_retailer: 'Чекене сатуучу',
      type_designer: 'Интерьер дизайнери',
      message: 'Бизнесиңиз жөнүндө кыскача айтып бериңиз',
      submit: 'Өнөктөштүккө арыз берүү',
      success_title: 'Арыз кабыл алынды!',
      success_desc: 'Кызыгууңуз үчүн рахмат. Биздин менеджер 24 сааттын ичинде сиз менен байланышып, дүң бааларды жана шарттарды талкуулайт.',
      back: 'Башкы бетке кайтуу'
    },
    ai: {
      welcome: "Саламатсызбы! Мен TamSal'дын экспертимин. Бүгүн пол же ПВХ панелдери боюнча сизге кантип жардам бере алам?",
      header: "TamSal Жардамчысы",
      status: "Онлайн | AI Консультант",
      input_ph: "Ламинат, ПВХ панелдери же орнотуу боюнча сураңыз...",
      fact_check: "Google аркылуу текшерилген"
    }
  },
  ru: {
    nav: { home: 'Главная', materials: 'Материалы', estimator: 'Калькулятор', locations: 'Адреса', partner: 'Партнерам' },
    hero: {
      tagline: 'Ведущий поставщик покрытий в Кыргызстане',
      title_part1: 'Построй свой',
      title_accent: 'Дом Мечты',
      title_part2: 'с TamSal',
      desc: 'Специализируемся на высококачественных ПВХ панелях, ламинате, линолеуме и профессиональных материалах для их монтажа.',
      cta_browse: 'Смотреть каталог',
      cta_ai: 'AI Калькулятор'
    },
    home: {
      core_inv: 'Наш ассортимент',
      core_desc: 'Лучший выбор стеновых панелей и напольных покрытий.',
      view_all: 'Посмотреть весь каталог',
      trust_logs: 'Быстрая логистика',
      trust_logs_desc: 'Собственный парк для доставки в день заказа по Бишкеку и пригородам.',
      trust_cert: 'Сертифицированное качество',
      trust_cert_desc: 'Прочные материалы, проверенные временем и климатом Кыргызстана.',
      trust_ai: 'AI Помощь',
      trust_ai_desc: 'Расчет материалов для пола и отделки стен доступен 24/7.'
    },
    catalog: {
      categories: 'Категории',
      search: 'Поиск товаров',
      results_for: 'Результаты для:',
      found: 'товаров найдено',
      add: 'Добавить',
      no_found: 'Товары не найдены',
      no_found_desc: 'Попробуйте изменить фильтры или поисковый запрос.'
    },
    calculator: {
      tag: 'Умные инструменты',
      title: 'Калькулятор проекта',
      desc: 'Рассчитайте необходимое количество ламината, линолеума или ПВХ панелей для вашего помещения.',
      proj_type: 'Тип проекта',
      proj_type_ph: 'напр.: укладка ламината, отделка ванной ПВХ панелями',
      dims: 'Размеры',
      dims_ph: 'напр.: 20 кв.м или 3м x 4м',
      btn: 'Рассчитать',
      btn_loading: 'Расчет...',
      results: 'Результаты',
      disclaimer: '* Примечание: Это оценки, сгенерированные ИИ. Всегда берите запас 5-10% на подрезку.'
    },
    contact: {
      title: 'Наши филиалы',
      open_2gis: '2GIS',
      open_gmaps: 'Google Карты',
      call: 'Позвонить',
      delivery_title: 'Доставка по Бишкеку',
      delivery_desc: 'Мы доставляем во все районы: Ленинский, Октябрьский, Первомайский, Свердловский и пригороды.',
      next_day_title: 'Доставка на следующий день',
      next_day_desc: 'Сделайте заказ до 16:00, чтобы получить материалы уже на следующий день. Наш автопарк гарантирует своевременное прибытие на ваш объект.',
      bulk_title: 'Оптовые скидки',
      bulk_desc: 'Планируете крупный проект? Мы предлагаем специальные цены для заказов свыше 100 кв.м. Свяжитесь с отделом продаж для получения КП.',
      quick_tip: 'Интерактивная карта',
      tip_desc: 'Выберите филиал слева, чтобы увидеть его на карте. Используйте 2GIS или Google Карты для навигации.'
    },
    cart: {
      title: 'Ваша корзина',
      empty: 'Корзина пуста',
      empty_desc: 'Добавьте материалы, чтобы начать.',
      remove: 'Удалить',
      subtotal: 'Итого',
      checkout: 'Оформить заказ',
      secure: 'Безопасная оплата через Kyrgyz Pay'
    },
    footer: {
      desc: 'TamSal: Специалисты по современным напольным покрытиям и отделке стен. Работаем для вас с 2010 года.',
      nav: 'Navigation',
      contact: 'Контакты',
      rights: '© 2024 TamSal. Все права защищены.',
      privacy: 'Политика конфиденциальности',
      terms: 'Условия использования',
      seismic: 'Стандарты качества'
    },
    partner: {
      title: 'Станьте партнером TamSal',
      subtitle: 'Присоединяйтесь к нашей сети профессиональных монтажников и подрядчиков в Бишкеке.',
      company: 'Название компании',
      contact: 'Контактное лицо',
      phone: 'Номер телефона',
      email: 'Электронная почта',
      type: 'Тип бизнеса',
      type_installer: 'Профессиональный монтажник',
      type_contractor: 'Генеральный подрядчик',
      type_retailer: 'Розничный продавец',
      type_designer: 'Дизайнер интерьера',
      message: 'Кратко опишите ваш бизнес',
      submit: 'Подать заявку',
      success_title: 'Заявка получена!',
      success_desc: 'Спасибо за интерес к партнерству. Наш менеджер свяжется с вами в течение 24 часов для обсуждения условий и оптовых цен.',
      back: 'На главную'
    },
    ai: {
      welcome: "Здравствуйте! Я ИИ-эксперт TamSal. Чем я могу помочь вам в подборе ламината или ПВХ панелей сегодня?",
      header: "Ассистент TamSal",
      status: "В сети | AI Консультант",
      input_ph: "Спросите о ламинате, ПВХ панелях или монтаже...",
      fact_check: "Проверено через Google"
    }
  }
};